name: Build Proton VPN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore ProtonVPN.sln

    - name: Build Executable
      run: msbuild ProtonVPN.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Finished Exe
      uses: actions/upload-artifact@v4
      with:
        name: ProtonVPN-Executable
        path: "**/bin/Release/**/*.exe"
